baseURL: "http://jhermosillad.github.io/"
title: Jesus Hermosilla
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
pluralizeListTitles: false

minify:
  disableXML: true
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true
    
params:
    author: Authors Name
    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    label:
        icon: "/logo.png"
        iconHeight: 35
    profileMode:
        enabled: true
        title: Jesus Eduardo Hermosilla Diaz
        subtitle: "Hello, I'm an enthusiastic physicist in computer science and artificial intelligence from Mexico."
        imageUrl: "/profile.png"
        imageTitle: Profile image
        imageWidth: 350
        imageHeight: 350
    socialIcons:
        - name: github
          url: "https://github.com/jhermosillad"
        - name: linkedin
          url: "https://www.linkedin.com/in/jesus-hermosilla/"
        - name: email
          url: "mailto:hermosilladiaz@gmail.com"
    mainSections:
        - posts
        - projects
        - teaching

menu:
  main:
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4