baseURL: "http://jhermosillad.github.io/"
title: Jesus Hermosilla
paginate: 5
theme: PaperMod

buildDrafts: true

minify:
  disableXML: true
  minifyOutput: true

markup:
  goldmark:
    renderer:
      unsafe: true
      
params:
    defaultTheme: dark
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: false
    ShowToc: false
    ShowBreadCrumbs: false
    label:
        icon: "/logo.png"
        iconHeight: 35
    profileMode:
        enabled: true
        title: Jesus Eduardo Hermosilla Diaz
        subtitle: "Hey there! I'm a physicist pursuing an artificial intelligence Ph.D. in Mexico. Here, I keep a record of my academic odyssey."
        imageUrl: "/profile.jpg"
        imageTitle: Profile image
        imageWidth: 350
        imageHeight: 350
    socialIcons:
        - name: github
          url: "https://github.com/jhermosillad"
        - name: linkedin
          url: "https://www.linkedin.com/in/jesus-hermosilla/"
        - name: email
          url: "mailto:hermosilladiaz@gmail.com"

menu:
  main:
    - identifier: resume
      name: Resume
      url: /resume/main
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 3